# Generated by Django 5.2.3 on 2025-08-15 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (rus)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='fas fa-tag', max_length=50, verbose_name='Ikonka')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Joylashuv',
                'verbose_name_plural': 'Joylarhuv',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('excellent', "Zo'r holatda"), ('good', 'Yaxshi holatda'), ('fair', 'Qoniqarli holatda'), ('poor', 'Yomon holatda')], default='good', max_length=20, verbose_name='Holati')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='Kelishish mumkin')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('sold', 'Sotildi'), ('expired', 'Muddati tugagan')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Tanlanganlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Tanlanganlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.category', verbose_name='Kategoriya')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.location', verbose_name='Joylashuv')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/%Y/%m/%d/', verbose_name='Rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad', verbose_name="E'lon")),
            ],
            options={
                'verbose_name': "E'lon rasmi",
                'verbose_name_plural': "E'lon rasmlari",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Nomaqbul kontent'), ('fraud', 'Firibgarlik'), ('duplicate', "Takroriy e'lon"), ('wrong_category', "Noto'g'ri kategoriya"), ('other', 'Boshqa')], max_length=20, verbose_name='Sabab')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal qilingan')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ads.ad', verbose_name="E'lon")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "E'lon shikoyati",
                'verbose_name_plural': "E'lon shikoyatlari",
                'ordering': ['-created_at'],
                'unique_together': {('ad', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category', 'location', 'is_active'], name='ads_ad_categor_ee8499_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['created_at'], name='ads_ad_created_9f5b83_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_featured', 'is_vip'], name='ads_ad_is_feat_523146_idx'),
        ),
    ]
