# Generated by Django 5.2.3 on 2025-08-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Joylashuv', 'verbose_name_plural': 'Joylashuvlar'},
        ),
    ]
